import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import ScoreRing from "@/components/ScoreRing";
import { CheckCircle, AlertTriangle, Lightbulb, Target, TrendingUp, FileCheck, Copy, Download, FileDown } from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";

export interface AnalysisResult {
  scores: {
    overall: number;
    ats: number;
    impact: number;
    clarity: number;
    relevance: number;
  };
  beforeScore: number;
  strengths: string[];
  weaknesses: string[];
  improvements: string[];
  missingKeywords: string[];
  improvedResume: string;
  suggestions: string[];
}

interface AnalysisResultsProps {
  result: AnalysisResult;
}

const AnalysisResults: React.FC<AnalysisResultsProps> = ({ result }) => {
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(result.improvedResume);
      toast.success("Resume copied to clipboard");
    } catch {
      toast.error("Failed to copy. Please select and copy manually.");
    }
  };

  const handleDownload = () => {
    const blob = new Blob([result.improvedResume], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "optimized-resume.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Resume downloaded");
  };

  const handlePdfExport = () => {
    try {
      const doc = new jsPDF();
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxWidth = pageWidth - margin * 2;
      let y = margin;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text("Optimized Resume", margin, y);
      y += 10;

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120);
      doc.text(`ATS Score: ${result.scores.overall}/100 | Generated by ResumeAI`, margin, y);
      doc.setTextColor(0);
      y += 10;

      doc.setDrawColor(200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;

      doc.setFontSize(10);
      const lines = doc.splitTextToSize(result.improvedResume, maxWidth);
      for (const line of lines) {
        if (y > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage();
          y = margin;
        }
        doc.text(line, margin, y);
        y += 5;
      }

      doc.save("optimized-resume.pdf");
      toast.success("PDF downloaded");
    } catch {
      toast.error("Failed to generate PDF");
    }
  };

  return (
    <div className="space-y-8 animate-fade-up">
      {/* Score Dashboard */}
      <Card className="shadow-elevated border-border overflow-hidden">
        <CardHeader className="bg-primary text-primary-foreground pb-4">
          <CardTitle className="flex items-center gap-2 text-lg">
            <TrendingUp className="w-5 h-5" />
            ATS Score: {result.beforeScore} → {result.scores.overall}
          </CardTitle>
          <p className="text-primary-foreground/70 text-sm">
            +{result.scores.overall - result.beforeScore} point improvement
          </p>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <ScoreRing score={result.scores.ats} label="ATS" />
            <ScoreRing score={result.scores.impact} label="Impact" />
            <ScoreRing score={result.scores.clarity} label="Clarity" />
            <ScoreRing score={result.scores.relevance} label="Relevance" />
          </div>
        </CardContent>
      </Card>

      {/* Strengths & Weaknesses */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="shadow-card">
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-success" />
              Strengths
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {result.strengths.map((s, i) => (
              <p key={i} className="text-sm text-foreground/80 flex gap-2">
                <span className="text-success mt-0.5 shrink-0">✓</span>
                {s}
              </p>
            ))}
          </CardContent>
        </Card>

        <Card className="shadow-card">
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-warning" />
              Areas to Improve
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {result.weaknesses.map((w, i) => (
              <p key={i} className="text-sm text-foreground/80 flex gap-2">
                <span className="text-warning mt-0.5 shrink-0">!</span>
                {w}
              </p>
            ))}
          </CardContent>
        </Card>
      </div>

      {/* Missing Keywords */}
      <Card className="shadow-card">
        <CardHeader className="pb-3">
          <CardTitle className="text-base flex items-center gap-2">
            <Target className="w-4 h-4 text-accent" />
            Missing Keywords to Add
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            {result.missingKeywords.map((kw, i) => (
              <Badge key={i} variant="secondary" className="bg-accent/10 text-accent-foreground border-accent/20 border">
                {kw}
              </Badge>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Improved Resume */}
      <Card className="shadow-elevated">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="text-base flex items-center gap-2">
              <FileCheck className="w-4 h-4 text-success" />
              Optimized Resume
            </CardTitle>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleCopy} className="text-xs gap-1.5 hover:bg-primary hover:text-primary-foreground transition-colors">
                <Copy className="w-3.5 h-3.5" />
                Copy Resume
              </Button>
              <Button variant="outline" size="sm" onClick={handleDownload} className="text-xs gap-1.5 hover:bg-primary hover:text-primary-foreground transition-colors">
                <Download className="w-3.5 h-3.5" />
                Download TXT
              </Button>
              <Button variant="default" size="sm" onClick={handlePdfExport} className="text-xs gap-1.5 bg-primary text-primary-foreground hover:bg-primary/90 transition-colors">
                <FileDown className="w-3.5 h-3.5" />
                Download PDF
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="bg-muted rounded-lg p-6 font-body text-sm leading-relaxed whitespace-pre-wrap text-foreground/90">
            {result.improvedResume}
          </div>
        </CardContent>
      </Card>

      {/* Download Section */}
      <Card className="shadow-elevated bg-gradient-to-r from-primary/5 to-accent/5 border-primary/20">
        <CardContent className="pt-6">
          <div className="text-center space-y-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Download Your Optimized Resume</h3>
              <p className="text-sm text-foreground/70">Save your improved resume in your preferred format</p>
            </div>
            <div className="flex flex-wrap gap-3 justify-center">
              <Button onClick={handleCopy} variant="outline" className="gap-2 hover-scale">
                <Copy className="w-4 h-4" />
                Copy to Clipboard
              </Button>
              <Button onClick={handleDownload} variant="outline" className="gap-2 hover-scale">
                <Download className="w-4 h-4" />
                Download as TXT
              </Button>
              <Button onClick={handlePdfExport} className="gap-2 hover-scale bg-primary text-primary-foreground hover:bg-primary/90">
                <FileDown className="w-4 h-4" />
                Download as PDF
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Further Suggestions */}
      <Card className="shadow-card">
        <CardHeader className="pb-3">
          <CardTitle className="text-base flex items-center gap-2">
            <Lightbulb className="w-4 h-4 text-accent" />
            Further Suggestions
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          {result.suggestions.map((s, i) => (
            <p key={i} className="text-sm text-foreground/80 flex gap-2">
              <span className="text-accent mt-0.5 shrink-0">→</span>
              {s}
            </p>
          ))}
        </CardContent>
      </Card>
    </div>
  );
};

export default AnalysisResults;
